### ISSUE TITLE
print ssh.hash_md5() output include MD5

### ISSUE THREAD

**Issue by lvs071103** [ojarva/python-sshpubkeys#17] opened 2016-09-13 07:25 UTC
print ssh.hash_md5() output include "MD5: xx:xx......"
openssl -lf key_file no

**Comment by ojarva** [comment] 2016-09-13 07:41
`ssh-keygen -l -E md5 -f .ssh/id_rsa` outputs

`8200 MD5:1a:ea:c6:e3:80:b7:3f:ed:7c:71:a0:1e:c2:e9:14:81 RSA`. So I'm closing this as invalid - `MD5:`, `SHA256:` and other prefixes are by design.

**Closed by ojarva** 2016-09-13 07:41 UTC
